<a href="https://colab.research.google.com/github/Morty00933/python/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

torch.cat() - объединение тензоров вдоль указанной оси.

In [ ]:
import torch

# Создание двух тензоров
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Объединение вдоль оси 0
result = torch.cat((x, y))
print(result)

tensor([1, 2, 3, 4, 5, 6])


torch.gather() - сбор значений из тензора в соответствии с указанными индексами.

In [ ]:
# Создание тензора
data = torch.tensor([[1, 2], [3, 4]])

# Индексы для сбора данных
indices = torch.tensor([[0, 1], [1, 0]])

# Сбор данных
result = torch.gather(data, 1, indices)
print(result)

tensor([[1, 2],
        [4, 3]])


torch.index_select() - выбор значений из тензора по указанным индексам.

In [ ]:
# Создание маски
mask = result > 2

# Выбор значений по маске
selected_values = torch.masked_select(result, mask)
print(selected_values)

tensor([4, 3])


torch.narrow() - выбор подтензора с использованием среза.

In [ ]:
# Выбор подтензора
narrowed = result.narrow(0, 0, 1)
print(narrowed)

tensor([[1, 2]])


torch.nonzero() - возвращает индексы ненулевых элементов в тензоре.

In [ ]:
# Создание тензора с нулями и ненулевыми элементами
tensor = torch.tensor([[0, 1, 0], [2, 0, 3]])

# Получение индексов ненулевых элементов
nonzero_indices = torch.nonzero(tensor)
print(nonzero_indices)

tensor([[0, 1],
        [1, 0],
        [1, 2]])


torch.reshape() - изменение формы тензора.

In [ ]:
# Изменение формы тензора
reshaped = result.view(2, 2)
print(reshaped)

tensor([[1, 2],
        [4, 3]])
